// Generated by gencpp from file rplidar_ros/StartMotor.msg
// DO NOT EDIT!


#ifndef RPLIDAR_ROS_MESSAGE_STARTMOTOR_H
#define RPLIDAR_ROS_MESSAGE_STARTMOTOR_H

#include <ros/service_traits.h>


#include <rplidar_ros/StartMotorRequest.h>
#include <rplidar_ros/StartMotorResponse.h>


namespace rplidar_ros
{

struct StartMotor
{

typedef StartMotorRequest Request;
typedef StartMotorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartMotor
} // namespace rplidar_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rplidar_ros::StartMotor > {
  static const char* value()
  {
    return "bd160db0cb9e838a10809e84d876d07a";
  }

  static const char* value(const ::rplidar_ros::StartMotor&) { return value(); }
};

template<>
struct DataType< ::rplidar_ros::StartMotor > {
  static const char* value()
  {
    return "rplidar_ros/StartMotor";
  }

  static const char* value(const ::rplidar_ros::StartMotor&) { return value(); }
};


// service_traits::MD5Sum< ::rplidar_ros::StartMotorRequest> should match 
// service_traits::MD5Sum< ::rplidar_ros::StartMotor > 
template<>
struct MD5Sum< ::rplidar_ros::StartMotorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rplidar_ros::StartMotor >::value();
  }
  static const char* value(const ::rplidar_ros::StartMotorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rplidar_ros::StartMotorRequest> should match 
// service_traits::DataType< ::rplidar_ros::StartMotor > 
template<>
struct DataType< ::rplidar_ros::StartMotorRequest>
{
  static const char* value()
  {
    return DataType< ::rplidar_ros::StartMotor >::value();
  }
  static const char* value(const ::rplidar_ros::StartMotorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rplidar_ros::StartMotorResponse> should match 
// service_traits::MD5Sum< ::rplidar_ros::StartMotor > 
template<>
struct MD5Sum< ::rplidar_ros::StartMotorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rplidar_ros::StartMotor >::value();
  }
  static const char* value(const ::rplidar_ros::StartMotorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rplidar_ros::StartMotorResponse> should match 
// service_traits::DataType< ::rplidar_ros::StartMotor > 
template<>
struct DataType< ::rplidar_ros::StartMotorResponse>
{
  static const char* value()
  {
    return DataType< ::rplidar_ros::StartMotor >::value();
  }
  static const char* value(const ::rplidar_ros::StartMotorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RPLIDAR_ROS_MESSAGE_STARTMOTOR_H
