// Generated by gencpp from file dnn_rotate/StringTriggerResponse.msg
// DO NOT EDIT!


#ifndef DNN_ROTATE_MESSAGE_STRINGTRIGGERRESPONSE_H
#define DNN_ROTATE_MESSAGE_STRINGTRIGGERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dnn_rotate
{
template <class ContainerAllocator>
struct StringTriggerResponse_
{
  typedef StringTriggerResponse_<ContainerAllocator> Type;

  StringTriggerResponse_()
    : response()  {
    }
  StringTriggerResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StringTriggerResponse_

typedef ::dnn_rotate::StringTriggerResponse_<std::allocator<void> > StringTriggerResponse;

typedef boost::shared_ptr< ::dnn_rotate::StringTriggerResponse > StringTriggerResponsePtr;
typedef boost::shared_ptr< ::dnn_rotate::StringTriggerResponse const> StringTriggerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dnn_rotate

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::dnn_rotate::StringTriggerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dnn_rotate/StringTriggerResponse";
  }

  static const char* value(const ::dnn_rotate::StringTriggerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n\
\n\
";
  }

  static const char* value(const ::dnn_rotate::StringTriggerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringTriggerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dnn_rotate::StringTriggerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dnn_rotate::StringTriggerResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DNN_ROTATE_MESSAGE_STRINGTRIGGERRESPONSE_H
