// Generated by gencpp from file dnn_rotate/StringTriggerRequest.msg
// DO NOT EDIT!


#ifndef DNN_ROTATE_MESSAGE_STRINGTRIGGERREQUEST_H
#define DNN_ROTATE_MESSAGE_STRINGTRIGGERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dnn_rotate
{
template <class ContainerAllocator>
struct StringTriggerRequest_
{
  typedef StringTriggerRequest_<ContainerAllocator> Type;

  StringTriggerRequest_()
    : object()  {
    }
  StringTriggerRequest_(const ContainerAllocator& _alloc)
    : object(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_type;
  _object_type object;





  typedef boost::shared_ptr< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StringTriggerRequest_

typedef ::dnn_rotate::StringTriggerRequest_<std::allocator<void> > StringTriggerRequest;

typedef boost::shared_ptr< ::dnn_rotate::StringTriggerRequest > StringTriggerRequestPtr;
typedef boost::shared_ptr< ::dnn_rotate::StringTriggerRequest const> StringTriggerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dnn_rotate

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d32a80a49357522333ff3e758d0474bf";
  }

  static const char* value(const ::dnn_rotate::StringTriggerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd32a80a493575223ULL;
  static const uint64_t static_value2 = 0x33ff3e758d0474bfULL;
};

template<class ContainerAllocator>
struct DataType< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dnn_rotate/StringTriggerRequest";
  }

  static const char* value(const ::dnn_rotate::StringTriggerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object\n\
";
  }

  static const char* value(const ::dnn_rotate::StringTriggerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringTriggerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dnn_rotate::StringTriggerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dnn_rotate::StringTriggerRequest_<ContainerAllocator>& v)
  {
    s << indent << "object: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DNN_ROTATE_MESSAGE_STRINGTRIGGERREQUEST_H
